import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import HeaderFooter from "@/components/Header/HeaderFooter";
import Footer from "@/components/Footer/Footer";
import "react-responsive-carousel/lib/styles/carousel.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont bg-gray-300 bg-opacity-40" suppressHydrationWarning={true}>
        <Header />
        <HeaderFooter />
        {children}
        <Footer />
      </body>
    </html>
  );
}
